gradle.projectsEvaluated {
    rootProject.tasks.register('diagnosticResolvedVersions') {
        doLast {
            def configuration = project(':app').configurations.getByName('debugAndroidTestRuntimeClasspath')
            def wanted = ['androidx.compose.ui:ui-test-junit4-android', 'androidx.compose.ui:ui-test-android', 'androidx.test:core', 'androidx.test.ext:junit']
            def values = configuration.incoming.resolutionResult.allComponents.collect { it.moduleVersion }.findAll { it != null && wanted.contains(it.group + ':' + it.name) }.collect { it.toString() }.sort()
            assert values.size() == wanted.size()
            def destination = new File(System.getenv('RUNNER_TEMP'), 'api34-resolved-versions.txt')
            destination.text = values.join('\n') + '\n'
            println destination.text
        }
    }
}
